[package]
name = "crustf-jar-builder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Pure Rust JAR / ZIP writer — no_std + alloc, WASM friendly"
keywords = ["jar", "zip", "jvm", "classfile", "archive"]
categories = ["encoding", "no-std"]

[features]
default = ["std"]
std = []

[lints]
workspace = true
